#!/usr/bin/env bash
set -eu
# assume already athenticated to vault
# TODO: change for diffrenet enviroments (prod / staging)
GOOGLE_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/staging/google)
GOOGLE_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/staging/google)
GITHUB_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/staging/github)
GITHUB_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/staging/github)
SESSION_SECRET=$(vault read -field=secret /secret/beebop/express-session)

kubectl -n beebop create secret generic auth-secrets \
  --from-literal=googleClientId="$GOOGLE_CLIENT_ID" \
  --from-literal=googleClientSecret="$GOOGLE_CLIENT_SECRET" \
  --from-literal=githubClientId="$GITHUB_CLIENT_ID" \
  --from-literal=githubClientSecret="$GITHUB_CLIENT_SECRET" \
  --from-literal=sessionSecret="$SESSION_SECRET"