#!/usr/bin/env bash
# TODO: update to use vault k8s auth
set -eu

export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
export VAULT_TOKEN=$(vault login -method=github -token-only)

# TODO: change for diffrenet enviroments (prod / staging)
GOOGLE_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/staging/google)
GOOGLE_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/staging/google)
GITHUB_CLIENT_ID=$(vault read -field=clientid /secret/beebop/auth/staging/github)
GITHUB_CLIENT_SECRET=$(vault read -field=secret /secret/beebop/auth/staging/github)
SESSION_SECRET=$(vault read -field=secret /secret/beebop/express-session)

kubectl create secret generic auth-secrets \
  --from-literal=googleClientId="$GOOGLE_CLIENT_ID" \
  --from-literal=googleClientSecret="$GOOGLE_CLIENT_SECRET" \
  --from-literal=githubClientId="$GITHUB_CLIENT_ID" \
  --from-literal=githubClientSecret="$GITHUB_CLIENT_SECRET" \
  --from-literal=sessionSecret="$SESSION_SECRET"