#!/usr/bin/env bash
# TODO: update to use vault k8s auth
set -eu

export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
export VAULT_TOKEN=$(vault login -method=github -token-only)

DEST=${PWD}/k8s/ssl
mkdir -p $DEST 

vault read -field=cert /secret/beebop/ssl/staging > \
      ${DEST}/certificate.pem
vault read -field=key /secret/beebop/ssl/staging > \
      ${DEST}/key.pem

kubectl -n beebop create secret tls tls-secret --cert  ${DEST}/certificate.pem --key ${DEST}/key.pem