docker:
  network: beebop_nw
  prefix: beebop
proxy:
  host: localhost
  port_http: 80
  port_https: 443
  image:
    repo: mrcide
    name: beebop-proxy
    tag: main
server:
  image:
    repo: mrcide
    name: beebop-server
    tag: main
  port: 4000
  redis_url: "redis://beebop-redis:6379"
api:
  image:
    repo: mrcide
    name: beebop-py
    # TODO: change back to main before merge
    tag: bacpop-159-use-v8
  db_location: ./storage/GPS_v8_ref
  storage_location: ./storage
redis:
  image:
    name: redis
    tag: "5.0"
worker:
  count: 1
