docker:
  network: beebop_nw
  prefix: beebop
  registry: ghcr.io
proxy:
  host: localhost
  port_http: 80
  port_https: 443
  image:
    repo: bacpop
    name: beebop-proxy
    tag: bacpop-208-nw-mc-1-call
server:
  image:
    repo: bacpop
    name: beebop-server
    tag: bacpop-208-nw-mc-1-call
  port: 4000
  redis_url: "redis://beebop-redis:6379"
api:
  image:
    repo: bacpop
    name: beebop-py
    tag: bacpop-208-nw-mc-1-call
  dbs_location: ./storage/dbs
  storage_location: ./storage
redis:
  image:
    name: redis
    tag: "5.0"
worker:
  count: 1
