server:
  client_url: https://localhost
  server_url: https://localhost/api
  auth:
    google:
      client_id: abcd
      secret: abcd
    session_secret: abcd
    github:
      client_id: abcd
      secret: abcd
worker:
  count: 2
download_ref_dbs_only: true