proxy:
  host: beebop.dide.ic.ac.uk
server:
  node_options: "--max-old-space-size=8192"
  client_url: https://beebop.dide.ic.ac.uk
  server_url: https://beebop.dide.ic.ac.uk/api
  auth:
    google:
      client_id: VAULT:secret/beebop/auth/production/google:clientid
      secret: VAULT:secret/beebop/auth/production/google:secret
    session_secret: VAULT:secret/beebop/express-session/production:secret
    github:
      client_id: VAULT:secret/beebop/auth/production/github:clientid
      secret: VAULT:secret/beebop/auth/production/github:secret
vault:
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    method: github
acme_buddy:
  image:
    repo: reside-ic
    name: acme-buddy
    tag: latest
  hdb_username: VAULT:secret/certbot-hdb/credentials:username
  hdb_password: VAULT:secret/certbot-hdb/credentials:password
  port: 2112
api:
  dbs_location: ./storage/dbs
worker:
  count: 5
