on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
      - "bacpop-*"

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install dependencies
        # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#installing-dependencies
        # If installing a development version of constellation, use:
        # - pip3 install git+https://github.com/reside-ic/constellation@reside-62#egg=constellation
        run: |
          python -m pip install --upgrade setuptools pip wheel
          pip3 install pytest-cov pycodestyle codecov
          pip3 install -r requirements.txt

      - name: Tests
        run: |
          pytest --cov=src

      - name: Lint
        run: |
          pycodestyle .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
